### PR TITLE
Fix notebooks to use UTC

### PR DESCRIPTION
**Pull request by SimonKrughoff**

### CODE REVIEW

**Review by afausti — APPROVED** [review]
Looks great, thanks for fixing these notebooks to use UTC. 
I was trying to recall when the change to UTC was introduced in the EFD and looking at DM-30082 it was around July 2021. Should we query data later than July 2021 to be consistent?

**Comment by SimonKrughoff** [comment]
That's a good question.  I'll see how easy it is to find new ranges after that date.

**Comment by SimonKrughoff** [comment]
OK.  I've modified the notebooks in question to use more modern messages.  Let me know what you think.

**Review by afausti — APPROVED** [review]
Perfect! thanks for using more modern data and fixing up the notebook text.

**Pull request merged**
